#ifndef PGDBA_GENERATORS_GLOBAL_H
#define PGDBA_GENERATORS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PGDBA_GENERATORS_LIBRARY)
#  define PGDBA_GENERATORSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PGDBA_GENERATORSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PGDBA_GENERATORS_GLOBAL_H
